import type { Expression, Requirement, RulePack } from './model';

const eq = (fact: string, value: string | number | boolean): Expression => ({
  op: 'eq',
  fact,
  value,
});
const all = (...expressions: Expression[]): Expression => ({ op: 'all', expressions });
const rule = (
  id: string,
  title: string,
  summary: string,
  check: Expression,
  question: string,
  options: Partial<Requirement> = {},
): Requirement => ({
  id: `gibc-${id}`,
  title: `GIBC: ${title}`,
  summary,
  check,
  question,
  scope: 'entry',
  category: 'participation',
  sources: ['gibc-rules'],
  correction: 'Review this requirement and the official source before submitting.',
  review: 'curated',
  rationale: 'Checks the declared facts for GIBC V2 only. This is not organizer approval.',
  ...options,
});

/** Selected checks for Open Invention only; not the LLM or Med/Finance tracks. */
export const gibcRulePack: RulePack = {
  id: 'gibc-v2-2026',
  version: '2026-09-22.1',
  title: 'GIBC V2 · Open Invention',
  start: '2026-07-11T04:00:00.000Z',
  deadline: '2026-10-01T15:45:00.000Z',
  updatedAt: '2026-09-22T07:00:00.000Z',
  reviewNote:
    'Selected Open Invention checks, curated with AI assistance. The other two tracks and sponsor prize conditions are outside coverage.',
  sources: [
    {
      id: 'gibc-rules',
      title: 'GIBC V2 official rules',
      url: 'https://gibc-v2.devpost.com/rules',
      publisher: 'GIBC V2 organizers on Devpost',
      capturedAt: '2026-09-22',
      version: 'captured-2026-09-22',
      authority: 'Event rules',
      quote: 'Enter alone or in a team of up to 6 people.',
      summary:
        'Student event. Rules cover participation, individual track constraints, development dates and required submission materials. Times use UTC+8.',
    },
    {
      id: 'gibc-overview',
      title: 'GIBC V2 overview',
      url: 'https://gibc-v2.devpost.com/',
      publisher: 'GIBC V2 organizers on Devpost',
      capturedAt: '2026-09-22',
      version: 'captured-2026-09-22',
      authority: 'Event overview and submission instructions',
      quote: 'Each team submits one project to one track.',
      summary:
        'Open Invention is one of three tracks. Its judges assess creativity, execution, impact and presentation. This pack covers selected entry and submission checks, not a prediction of those scores.',
    },
  ],
  requirements: [
    rule(
      'team',
      'Team size',
      'One to six members.',
      { op: 'lte', fact: 'teamSize', value: 6 },
      'How many people are on this team?',
    ),
    rule(
      'students',
      'Student participation',
      'Every participant must be a student.',
      eq('allStudents', true),
      'Is every member a student?',
    ),
    rule(
      'age',
      'Minimum age',
      'Participants are 13 or older.',
      { op: 'gte', fact: 'minimumAge', value: 13 },
      'How old is the youngest team member?',
    ),
    rule(
      'guardian',
      'Guardian permission',
      'Under-18 participants should have guardian permission.',
      eq('guardianConsent', true),
      'Do all under-18 members have guardian permission?',
      { appliesWhen: { op: 'lte', fact: 'minimumAge', value: 17 }, review: 'needs-organizer' },
    ),
    rule(
      'residency',
      'Residency restrictions',
      'Devpost exclusions and applicable restrictions apply.',
      eq('eligibleResidency', true),
      'Has every member checked GIBC’s location restrictions?',
    ),
    rule(
      'affiliation',
      'Organizer affiliations',
      'Organizers, judges and immediate family are excluded.',
      eq('excludedAffiliation', false),
      'Is any member an organizer, judge or immediate family member?',
    ),
    rule(
      'one-team',
      'One submitting team',
      'One team per person; one project in one track.',
      all(eq('oneTeam', true), eq('entriesPerPath', 1)),
      'Is every member on one team, entering one project in one track?',
      { sources: ['gibc-rules', 'gibc-overview'] },
    ),
    rule(
      'start',
      'Development start',
      'Build during July 11–October 1, 2026.',
      all(
        { op: 'date-after', fact: 'startedAt', value: '2026-07-11T04:00:00.000Z' },
        { op: 'date-after', fact: '$deadline', value: '$startedAt' },
      ),
      'When did development begin? Include a timezone on the opening day.',
      { category: 'prior-work' },
    ),
    rule(
      'origin',
      'New entry',
      'Pre-existing projects are excluded.',
      { op: 'any', expressions: [eq('origin', 'new'), eq('origin', 'components')] },
      'What existed before GIBC opened on July 11?',
      { category: 'prior-work' },
    ),
    rule(
      'previous-entry',
      'Previous hackathon entry',
      'Substantially repeated hackathon entries are excluded.',
      eq('priorHackathonEntry', false),
      'Is this substantially the same as a previous hackathon entry?',
      { category: 'prior-work' },
    ),
    rule(
      'prototype',
      'Open Invention prototype',
      'Demonstrate a working prototype with technical novelty.',
      all(eq('workingPrototype', true), eq('technicalNovelty', true)),
      'Does a working prototype demonstrate technical novelty?',
      {
        scope: 'path',
        category: 'sponsor',
        rationale: 'These are declarations. Judges assess novelty; FinePrint does not verify it.',
      },
    ),
    rule(
      'repository',
      'Source and setup',
      'Public source and a setup/usage README are required.',
      all(eq('publicRepository', true), eq('setupInstructions', true)),
      'Is the public repository complete with setup and usage instructions?',
      { scope: 'submission', category: 'artifacts', sources: ['gibc-overview'] },
    ),
    rule(
      'video',
      'Demo video',
      'Accessible 2–5 minute running demo, on YouTube, Vimeo or Youku.',
      all(
        { op: 'gte', fact: 'videoMinutes', value: 2 },
        { op: 'lte', fact: 'videoMinutes', value: 5 },
        eq('videoAccessible', true),
      ),
      'How long is the accessible running demo on an accepted video host?',
      { scope: 'submission', category: 'artifacts', sources: ['gibc-overview'] },
    ),
    rule(
      'screenshots',
      'Screenshots',
      'Submit at least three images.',
      { op: 'gte', fact: 'screenshotsCount', value: 3 },
      'How many screenshots are in the submission?',
      { scope: 'submission', category: 'artifacts', sources: ['gibc-overview'] },
    ),
    rule(
      'devpost',
      'Devpost materials',
      'Complete description, technology list and full team details.',
      eq('devpostComplete', true),
      'Are the description, complete Built With and full names/accounts of all members included?',
      { scope: 'submission', category: 'artifacts', sources: ['gibc-overview'] },
    ),
    rule(
      'english',
      'English materials',
      'Descriptions, documentation and demos use English.',
      eq('englishSubmission', true),
      'Are the submission and documentation in English, with English demo audio or subtitles?',
      { scope: 'submission', category: 'artifacts' },
    ),
    rule(
      'ai-disclosure',
      'AI coding disclosure',
      'Disclose AI coding assistance in Built With and README.',
      eq('aiUseDisclosed', true),
      'Have you disclosed the AI tools and assisted parts?',
      { scope: 'submission', category: 'artifacts', appliesWhen: eq('aiBuilt', true) },
    ),
    rule(
      'deadline',
      'Submission deadline',
      'Submit by October 1, 15:45 UTC.',
      { op: 'date-after', fact: '$deadline', value: '$now' },
      'Has the submission deadline passed?',
      { scope: 'submission', category: 'artifacts' },
    ),
  ],
};
