import type { Dossier, Expression, Requirement, RulePack } from './model';

const eq = (fact: string, value: string | number | boolean): Expression => ({
  op: 'eq',
  fact,
  value,
});
const any = (...expressions: Expression[]): Expression => ({ op: 'any', expressions });
const all = (...expressions: Expression[]): Expression => ({ op: 'all', expressions });
const reused = any(eq('origin', 'components'), eq('origin', 'existing'));
const pathOne = any(eq('track', 'path-one'), eq('track', 'both'));
const pathTwo = any(eq('track', 'path-two'), eq('track', 'both'));

export const rulePack: RulePack = {
  id: 'sanity-2026',
  version: '2026-09-20.1',
  title: 'Sanity Challenge',
  start: '2026-09-18T16:00:00.000Z',
  deadline: '2026-10-05T06:59:00.000Z',
  updatedAt: '2026-09-20T12:00:00.000Z',
  reviewNote:
    'AI-assisted source curation. Interpretations are not organizer approvals. Review the official pages before entering.',
  sources: [
    {
      id: 'faq',
      title: 'Challenge brief & FAQ',
      url: 'https://dev.to/challenges/sanity-2026-09-16',
      publisher: 'DEV Community',
      capturedAt: '2026-09-20',
      version: 'snapshot-2026-09-20',
      authority: 'Event instructions and FAQ',
      quote: 'No, only one submission per path is allowed.',
      summary:
        'The FAQ limits teams to four and submissions to one per path. It permits both paths with separate posts. Reused work needs significant changes and credit. Prize submissions need English. It sets sponsor and submission requirements.',
    },
    {
      id: 'contest',
      title: 'Sanity contest rules',
      url: 'https://dev.to/page/sanity-challenge-v26-09-16-contest-rules',
      publisher: 'DEV Community',
      capturedAt: '2026-09-20',
      version: 'snapshot-2026-09-20',
      authority: 'Event-specific contest rules',
      quote: 'There is no limit on the number of Entries you may submit during the Entry Period.',
      summary:
        'The entry period runs from September 18 at 9:00 AM PDT to October 4 at 11:59 PM PDT. A project ID or public dataset URL and a DEV post are required. A tie across paths favors someone who has not won a path. General rules take precedence over conflicting event-specific terms.',
    },
    {
      id: 'general',
      title: 'General contest rules',
      url: 'https://dev.to/page/official-hackathon-rules',
      publisher: 'Major League Hacking / DEV',
      capturedAt: '2026-09-20',
      version: 'updated-2026-02-25; captured-2026-09-20',
      authority: 'General rules; expressly control conflicting contest-announcement terms',
      quote: 'development of your Entry was started during, and not prior to, the Entry Period',
      summary:
        'Entry development must start during the event. Every team member must meet age, residence, account, and affiliation requirements. Additional restrictions and entrant warranties apply. General rules expressly control conflicting contest-announcement terms.',
    },
  ],
  requirements: [
    {
      id: 'team',
      title: 'Team size',
      scope: 'entry',
      category: 'participation',
      summary: 'No more than four people on the team.',
      sources: ['faq'],
      check: { op: 'lte', fact: 'teamSize', value: 4 },
      question: 'How many people are on this team?',
      correction: 'A team larger than four does not satisfy this requirement.',
      review: 'curated',
      rationale: 'This limit applies to the whole team, in either path.',
    },
    {
      id: 'age',
      title: 'Age of every team member',
      scope: 'entry',
      category: 'participation',
      summary: 'Each participant must meet the stated age and contracting requirements.',
      sources: ['general'],
      check: eq('adultTeam', true),
      question:
        'Does every team member meet the age and legal-majority requirement in the general rules?',
      correction: 'Resolve the ineligible team member before treating the team as eligible.',
      review: 'curated',
      rationale: 'A declaration covers all members; one eligible team leader is insufficient.',
    },
    {
      id: 'residency',
      title: 'Residency restrictions',
      scope: 'entry',
      category: 'participation',
      summary: 'Every participant must meet the listed residency and restricted-party conditions.',
      sources: ['general'],
      check: eq('eligibleResidency', true),
      question:
        'Has every member checked their residence and restricted-party status against the general rules?',
      correction: 'A listed or otherwise restricted participant prevents a supported finding.',
      review: 'curated',
      rationale:
        'Country of residence is not the same as nationality. This declaration does not perform sanctions screening.',
    },
    {
      id: 'membership',
      title: 'DEV membership',
      scope: 'entry',
      category: 'participation',
      summary: 'Participants need active DEV accounts in good standing.',
      sources: ['general'],
      check: eq('devMembership', true),
      question: 'Do all members have active DEV accounts in good standing?',
      correction: 'Create or restore the required DEV membership before entering.',
      review: 'curated',
      rationale: 'The app records your declaration; it does not inspect DEV account status.',
    },
    {
      id: 'affiliation',
      title: 'Organizer affiliations',
      scope: 'entry',
      category: 'participation',
      summary: 'Excluded organizer relationships make a participant ineligible.',
      sources: ['general'],
      check: eq('excludedAffiliation', false),
      question:
        'Does any member have an excluded employment, family, or household relationship listed in the general rules?',
      correction: 'Review the relationship with the organizer before proceeding.',
      review: 'curated',
      rationale: 'The requirement extends beyond direct employment. Answer for the whole team.',
    },
    {
      id: 'origin',
      title: 'Existing project or new entry?',
      scope: 'entry',
      category: 'prior-work',
      summary: 'The entry itself must begin during the competition.',
      sources: ['general', 'faq'],
      check: any(eq('origin', 'new'), eq('origin', 'components')),
      question:
        'Did the submitted application already exist, or are you reusing components in a new entry?',
      correction:
        'An existing entry is not made new merely by adding a sponsor integration. Ask the organizer about your exact scope.',
      review: 'curated',
      rationale:
        'Permission to reuse material does not explicitly exempt a pre-existing entry from the development-window requirement. Reusing components and resubmitting an application are different facts.',
    },
    {
      id: 'start',
      title: 'Development start',
      scope: 'entry',
      category: 'prior-work',
      summary: 'Development starts within the official entry period.',
      sources: ['general', 'contest'],
      check: all(
        { op: 'date-after', fact: 'startedAt', value: '2026-09-18T16:00:00.000Z' },
        { op: 'date-after', fact: '$deadline', value: '$startedAt' },
      ),
      question:
        'When did development of this entry start? For September 18, include the time and time zone.',
      correction: 'A start before the event does not satisfy the development-window requirement.',
      review: 'curated',
      rationale:
        'A repository creation date alone cannot establish when the entry was developed. A date that overlaps the opening time remains unknown.',
    },
    {
      id: 'credit',
      title: 'Credit for reused material',
      scope: 'entry',
      category: 'prior-work',
      summary: 'Credit non-trivial prior work.',
      sources: ['faq'],
      appliesWhen: reused,
      check: eq('priorWorkCredited', true),
      question: 'Have you identified and credited the non-trivial prior work used in this entry?',
      correction: 'Document the original material and its author in the submission.',
      review: 'curated',
      rationale:
        'Attribution applies when material is reused; it does not establish that the entry is otherwise eligible.',
    },
    {
      id: 'new-work',
      title: 'Substantial new work',
      scope: 'entry',
      category: 'prior-work',
      summary: 'Reused work must receive significant changes.',
      sources: ['faq'],
      appliesWhen: reused,
      check: eq('substantialNewWork', true),
      question: 'Have you described substantial changes made during the event?',
      correction:
        'Describe the actual new work. The organizer decides whether it is significant enough.',
      review: 'curated',
      rationale:
        'No numerical threshold is published. This finding records the declaration, not an assessment of significance.',
    },
    {
      id: 'context',
      title: 'Sanity Context + Knowledge Base',
      scope: 'path',
      category: 'sponsor',
      summary: 'Path One uses an agent connected to a Knowledge Base through Context MCP.',
      sources: ['faq'],
      appliesWhen: pathOne,
      check: all(eq('usesContext', true), eq('usesKnowledgeBase', true)),
      question: 'Does your agent actually read a Sanity Knowledge Base through Context MCP?',
      correction: 'Connect the agent to the required endpoint and demonstrate a real retrieval.',
      review: 'curated',
      rationale:
        'An ordinary database query, a local rule pack, or a configured endpoint alone is not evidence of a successful agent connection.',
    },
    {
      id: 'path-two',
      title: 'Path Two build requirements',
      scope: 'path',
      category: 'sponsor',
      summary: 'Path Two uses AI coding, Next.js or Astro, and Sanity.',
      sources: ['faq'],
      appliesWhen: pathTwo,
      check: all(eq('aiBuilt', true), eq('supportedFrontend', true), eq('usesSanity', true)),
      question: 'Was the app built with an AI coding tool, using Next.js or Astro with Sanity?',
      correction: 'Supply the required frontend, Sanity usage, and an honest build account.',
      review: 'curated',
      rationale: 'These conditions belong to Path Two and are not added to a Path One-only entry.',
    },
    {
      id: 'entry-limit',
      title: 'Entries in the same path',
      scope: 'entry',
      category: 'participation',
      summary: 'The FAQ and contest rules disagree about the submission limit.',
      sources: ['faq', 'contest'],
      check: { op: 'lte', fact: 'entriesPerPath', value: 1 },
      question:
        'Which submission limit governs multiple entries in the same path: the FAQ limit or the event rules?',
      correction: 'Request an organizer ruling before planning multiple entries in the same path.',
      review: 'needs-organizer',
      rationale:
        'One entry satisfies both statements. More than one activates the discrepancy; it is not automatically declared permitted or prohibited.',
    },
    {
      id: 'separate-posts',
      title: 'A post for each path',
      scope: 'submission',
      category: 'artifacts',
      summary: 'Entering both paths requires a separate submission post for each.',
      sources: ['faq'],
      appliesWhen: eq('track', 'both'),
      check: eq('separatePosts', true),
      question: 'Do you have a separate submission post for each path?',
      correction: 'Prepare separate posts using the relevant path templates.',
      review: 'curated',
      rationale:
        'Permission to enter both paths does not decide whether both prizes may be received.',
    },
    {
      id: 'english',
      title: 'Language for prize judging',
      scope: 'prize',
      category: 'prize-compatibility',
      summary: 'Prize submissions must be in English.',
      sources: ['faq'],
      check: eq('englishSubmission', true),
      question: 'Is the submission in English for prize judging?',
      correction: 'Provide an English submission to satisfy this prize requirement.',
      review: 'curated',
      rationale:
        'The FAQ allows non-English submissions for a completion badge. This finding affects prize eligibility, not the same question as permission to participate.',
    },
    {
      id: 'combination',
      title: 'Receiving prizes in both paths',
      scope: 'combination',
      category: 'prize-compatibility',
      summary:
        'The tie-break provision does not provide unconditional permission to receive both prizes.',
      sources: ['contest'],
      appliesWhen: eq('seeksMultiplePrizes', true),
      check: { op: 'unresolved' },
      question:
        'Can one participant receive prizes in both paths outside the stated tie-break situation?',
      correction: 'Ask the organizer to confirm the intended prize combination.',
      review: 'needs-organizer',
      rationale:
        'A provision describing a tie across paths is not a general prize-stacking entitlement.',
    },
    {
      id: 'access',
      title: 'Access for judges',
      scope: 'submission',
      category: 'artifacts',
      summary: 'An app with login needs testing credentials or testing instructions.',
      sources: ['faq'],
      appliesWhen: eq('requiresLogin', true),
      check: eq('judgeAccess', true),
      question:
        'Have you provided safe testing credentials or clear testing instructions for judges?',
      correction:
        'Provide judge access instructions in the submission. Do not publish a personal password.',
      review: 'curated',
      rationale:
        'A public landing page does not show that judges can use the application. No credential is collected by FinePrint.',
    },
    {
      id: 'identifier',
      title: 'Sanity project details',
      scope: 'submission',
      category: 'artifacts',
      summary: 'Include a Sanity project ID or a public dataset URL.',
      sources: ['contest'],
      check: { op: 'present', fact: 'projectIdentifier' },
      question: 'What Sanity project ID or public dataset URL will your submission include?',
      correction: 'Add the project identifier or public dataset URL to the submission.',
      review: 'curated',
      rationale:
        'Presence is checked here. Ownership, content, accessibility, and the actual integration still need verification.',
    },
    {
      id: 'post',
      title: 'Published submission',
      scope: 'submission',
      category: 'artifacts',
      summary: 'Publish the DEV submission with its required challenge tag.',
      sources: ['contest', 'faq'],
      check: all(eq('publishedPost', true), eq('hasChallengeTag', true)),
      question: 'Is the DEV submission published with the sanitychallenge tag?',
      correction: 'Publish the correct template and include the required tag before the deadline.',
      review: 'curated',
      rationale: 'A draft or a local report is not a submitted entry or a receipt.',
    },
    {
      id: 'deadline',
      title: 'Submission window',
      scope: 'submission',
      category: 'artifacts',
      summary: 'Submit during the official entry period.',
      sources: ['contest'],
      check: all(
        { op: 'date-after', fact: '$now', value: '2026-09-18T16:00:00.000Z' },
        { op: 'date-after', fact: '$deadline', value: '$now' },
      ),
      question: 'Recheck the current submission window against the official event page.',
      correction: 'The recorded submission window is closed or has not opened.',
      review: 'curated',
      rationale:
        'The deadline is October 4, 2026 at 11:59 PM PDT. The organizer’s receipt, not this report, confirms submission.',
    },
  ] satisfies Requirement[],
};

export const blankDossier: Dossier = {
  eventId: 'sanity-2026',
  allStudents: null,
  minimumAge: null,
  guardianConsent: null,
  oneTeam: null,
  workingPrototype: null,
  technicalNovelty: null,
  priorHackathonEntry: null,
  publicRepository: null,
  setupInstructions: null,
  videoMinutes: null,
  videoAccessible: null,
  screenshotsCount: null,
  devpostComplete: null,
  aiUseDisclosed: null,
  name: 'My project',
  track: 'path-one',
  origin: null,
  startedAt: null,
  teamSize: null,
  adultTeam: null,
  eligibleResidency: null,
  devMembership: null,
  excludedAffiliation: null,
  priorWorkCredited: null,
  substantialNewWork: null,
  usesSanity: null,
  usesContext: null,
  usesKnowledgeBase: null,
  aiBuilt: null,
  supportedFrontend: null,
  entriesPerPath: 1,
  separatePosts: null,
  englishSubmission: null,
  requiresLogin: null,
  judgeAccess: null,
  projectIdentifier: null,
  publishedPost: null,
  hasChallengeTag: null,
  seeksMultiplePrizes: false,
  evidenceNote: '',
};

export const examples: { id: string; name: string; description: string; dossier: Dossier }[] = [
  {
    id: 'new',
    name: 'New entry',
    description: 'A new application using an existing UI component.',
    dossier: {
      ...blankDossier,
      name: 'Atlas Notes',
      origin: 'components',
      startedAt: '2026-09-19',
      teamSize: 1,
      adultTeam: true,
      eligibleResidency: true,
      devMembership: true,
      excludedAffiliation: false,
      priorWorkCredited: true,
      substantialNewWork: true,
      usesSanity: true,
      usesContext: true,
      usesKnowledgeBase: true,
      englishSubmission: true,
      requiresLogin: false,
      evidenceNote:
        'Illustrative project: a new field-notes app built during the event. An existing date-picker is credited. All integration facts in this example are fictional declarations.',
    },
  },
  {
    id: 'existing',
    name: 'Existing app',
    description: 'An older application with a new Sanity feature.',
    dossier: {
      ...blankDossier,
      name: 'Atlas Notes',
      origin: 'existing',
      startedAt: '2026-08-23',
      teamSize: 1,
      adultTeam: true,
      eligibleResidency: true,
      devMembership: true,
      excludedAffiliation: false,
      priorWorkCredited: true,
      substantialNewWork: true,
      usesSanity: true,
      usesContext: true,
      usesKnowledgeBase: true,
      englishSubmission: true,
      requiresLogin: false,
      evidenceNote:
        'Illustrative project: the application existed before the competition. A new feature was added during the event. These are fictional declarations, not evidence about a real project.',
    },
  },
  {
    id: 'conflict',
    name: 'Two entries',
    description: 'A second submission activates conflicting instructions.',
    dossier: {
      ...blankDossier,
      name: 'Two planned entries',
      origin: 'new',
      startedAt: '2026-09-19',
      teamSize: 1,
      adultTeam: true,
      eligibleResidency: true,
      devMembership: true,
      excludedAffiliation: false,
      usesSanity: true,
      usesContext: true,
      usesKnowledgeBase: true,
      entriesPerPath: 2,
      englishSubmission: true,
      requiresLogin: false,
      evidenceNote: 'Illustrative scenario: two distinct entries are planned for Path One.',
    },
  },
];
